name: hola mundo

on: 
  workflow_dispatch: 
  #schedule:
  # - cron: "*/5 * * * *"  #se ejecuta cada 5 minutos
  push:
    branches: 
      - main
    paths:      # se ejecutará solamente cuando haya una modificación en una ruta o archivo específico
      - 'codigo/**'
      - '.github/workflows/hola-mundo.yml'
  pull_request:
    branches:
      -main

jobs:
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje hola mundo
        run: echo "Hola mundo, Jesús"
        
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Listar los archivos del repositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
