name: Issues ejemplo

on:
  issues:
    types: [opened]

jobs:
  procesa-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra el título del issue
        run: echo "El título del issue es ${{ github.event.issue.title }}"
    
